# Generated by Django 6.0 on 2026-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='punch_id',
            field=models.CharField(blank=True, help_text='Employee Punch ID', max_length=100, null=True, unique=True),
        ),
    ]
