# Generated by Django 6.0 on 2026-01-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0002_userprofile_punch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidPunchID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_id', models.CharField(help_text='Employee Punch ID', max_length=100, unique=True)),
                ('employee_name', models.CharField(blank=True, help_text='Employee name (optional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Punch ID is active and can be used for registration')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this Punch ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_punch_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valid Punch ID',
                'verbose_name_plural': 'Valid Punch IDs',
                'db_table': 'valid_punch_ids',
                'ordering': ['punch_id'],
            },
        ),
    ]
