# Generated by Django 6.0 on 2026-01-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0003_validpunchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days',
            field=models.CharField(help_text='Comma-separated list of delivery days (e.g., "Monday, Tuesday, Wednesday")', max_length=255),
        ),
    ]
