# Generated by Django 6.0 on 2026-01-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0004_alter_supplier_delivery_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_time_window',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days',
            field=models.JSONField(default=dict, help_text='JSON object with delivery days as keys and cutoff times as values (e.g., {"Monday": "14:00", "Tuesday": "15:00"})'),
        ),
    ]
