# Generated by Django 6.0 on 2026-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0005_remove_supplier_delivery_time_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('packaging', 'Packaging'), ('food', 'Food'), ('beverage', 'Beverage'), ('equipment', 'Equipment'), ('cleaning', 'Cleaning Supplies'), ('other', 'Other')], default='other', help_text='Supplier category', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person name', max_length=255, null=True),
        ),
    ]
