# Generated by Django 6.0 on 2026-01-05 09:14

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate_data(apps, schema_editor):
    """Create SupplierCategory table and migrate existing category data"""
    SupplierCategory = apps.get_model('maainventory', 'SupplierCategory')
    Supplier = apps.get_model('maainventory', 'Supplier')
    
    # Create category mapping
    category_mapping = {
        'packaging': 'Packaging',
        'food': 'Food',
        'beverage': 'Beverage',
        'equipment': 'Equipment',
        'cleaning': 'Cleaning Supplies',
        'other': 'Other',
    }
    
    # Create all categories
    created_categories = {}
    for key, name in category_mapping.items():
        category, created = SupplierCategory.objects.get_or_create(name=name)
        created_categories[key] = category
    
    # Migrate existing supplier categories
    for supplier in Supplier.objects.all():
        if supplier.category:  # If category field exists and has a value
            category_key = supplier.category.lower() if isinstance(supplier.category, str) else supplier.category
            if category_key in created_categories:
                supplier.category_id = created_categories[category_key].id
                supplier.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert back to string"""
    Supplier = apps.get_model('maainventory', 'Supplier')
    SupplierCategory = apps.get_model('maainventory', 'SupplierCategory')
    
    category_mapping = {
        'Packaging': 'packaging',
        'Food': 'food',
        'Beverage': 'beverage',
        'Equipment': 'equipment',
        'Cleaning Supplies': 'cleaning',
        'Other': 'other',
    }
    
    for supplier in Supplier.objects.all():
        if supplier.category_id:
            category = SupplierCategory.objects.get(id=supplier.category_id)
            supplier.category = category_mapping.get(category.name, 'other')
            supplier.save()


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0006_supplier_category_supplier_contact_person'),
    ]

    operations = [
        # Step 1: Create SupplierCategory model
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Packaging, Food, Beverage)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier Category',
                'verbose_name_plural': 'Supplier Categories',
                'db_table': 'supplier_categories',
                'ordering': ['name'],
            },
        ),
        # Step 2: Add temporary integer field for category
        migrations.AddField(
            model_name='supplier',
            name='category_temp',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 3: Migrate data
        migrations.RunPython(create_categories_and_migrate_data, reverse_migration),
        # Step 4: Remove old category field
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        # Step 5: Rename temp field to category and make it ForeignKey
        migrations.RenameField(
            model_name='supplier',
            old_name='category_temp',
            new_name='category',
        ),
        # Step 6: Alter field to ForeignKey
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Supplier category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='maainventory.suppliercategory'),
        ),
    ]
