# Generated by Django 6.0 on 2026-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0007_create_supplier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches that use this supplier item', related_name='supplier_items', to='maainventory.branch'),
        ),
    ]
