# Generated by Django 6.0 on 2026-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0008_supplieritem_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(blank=True, help_text='Lead time in days for orders from this supplier', null=True),
        ),
    ]
