# Generated by Django 6.0 on 2026-01-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0009_supplier_lead_time_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='lead_time_days',
        ),
    ]
