# Generated by Django 6.0 on 2026-01-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0010_remove_supplier_lead_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='order_days',
            field=models.JSONField(default=dict, help_text='JSON object with order days as keys and cutoff times as values (e.g., {"Monday": "17:00", "Wednesday": "18:00"})'),
        ),
    ]
