# Generated by Django 6.0 on 2026-01-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0011_supplier_order_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit name (e.g., pcs, kg, box)', max_length=50, unique=True)),
                ('abbreviation', models.CharField(help_text='Abbreviation (e.g., pcs, kg, bx)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the unit', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this unit active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Unit',
                'verbose_name_plural': 'Base Units',
                'db_table': 'base_units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Base unit for this supplier item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_items', to='maainventory.baseunit'),
        ),
    ]
