# Generated by Django 6.0 on 2026-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0012_baseunit_supplieritem_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='item_code',
            field=models.CharField(blank=True, help_text='Auto-generated item code based on category', max_length=50, null=True, unique=True),
        ),
    ]
