# Generated by Django 6.0 on 2026-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0013_supplieritem_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieritem',
            name='lead_time_days',
            field=models.IntegerField(blank=True, default=0, help_text='Lead time in days for orders from this supplier', null=True),
        ),
    ]
