# Generated by Django 6.0 on 2026-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0014_alter_supplieritem_lead_time_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='default_price',
        ),
        migrations.AddField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit for this item', max_digits=10, null=True),
        ),
    ]
