# Generated by Django 6.0 on 2026-01-07 04:56

from django.db import migrations, models


def migrate_branches_to_item(apps, schema_editor):
    """Migrate branches from SupplierItem to Item"""
    Item = apps.get_model('maainventory', 'Item')
    SupplierItem = apps.get_model('maainventory', 'SupplierItem')
    
    # For each item, collect all branches from its SupplierItems
    for item in Item.objects.all():
        # Get all branches from SupplierItems associated with this item
        supplier_items = SupplierItem.objects.filter(item=item)
        all_branches = set()
        
        for supplier_item in supplier_items:
            # Get branches from the old SupplierItem.branches field
            branches = supplier_item.branches.all()
            all_branches.update(branches)
        
        # Set branches on the Item
        if all_branches:
            item.branches.set(all_branches)


def reverse_migrate_branches(apps, schema_editor):
    """Reverse migration: move branches from Item back to SupplierItem"""
    Item = apps.get_model('maainventory', 'Item')
    SupplierItem = apps.get_model('maainventory', 'SupplierItem')
    
    # For each SupplierItem, set branches from its Item
    for supplier_item in SupplierItem.objects.all():
        if supplier_item.item:
            # Copy branches from Item to SupplierItem
            branches = supplier_item.item.branches.all()
            supplier_item.branches.set(branches)


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0015_remove_item_default_price_item_price_per_unit'),
    ]

    operations = [
        # First, add the branches field to Item
        migrations.AddField(
            model_name='item',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches that use this item', related_name='items', to='maainventory.branch'),
        ),
        # Migrate data from SupplierItem.branches to Item.branches
        migrations.RunPython(migrate_branches_to_item, reverse_migrate_branches),
        # Then remove the branches field from SupplierItem
        migrations.RemoveField(
            model_name='supplieritem',
            name='branches',
        ),
    ]
