# Generated by Django 6.0 on 2026-01-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0016_move_branches_to_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Photo for this item', upload_to='item_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Display order for photos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maainventory.item')),
            ],
            options={
                'db_table': 'item_photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
