# Generated by Django 6.0 on 2026-01-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0017_add_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Signed', 'Signed'), ('Confirmed', 'Confirmed'), ('InProduction', 'In Production'), ('Ready', 'Ready'), ('PartiallyReceived', 'Partially Received'), ('Received', 'Received'), ('OnHold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
