# Generated by Django 6.0 on 2026-01-11 08:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0018_alter_supplierorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Notified', 'Notified'), ('InProduction', 'In Production'), ('Ready', 'Ready'), ('MovedToStock', 'Moved to Stock'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('delivery_days_min', models.IntegerField(help_text='Minimum delivery days (e.g., 50)', validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_days_max', models.IntegerField(help_text='Maximum delivery days (e.g., 70)', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes for supplier', null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_item_requests', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='maainventory.supplier')),
            ],
            options={
                'db_table': 'item_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_request_items', to='maainventory.item')),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maainventory.itemrequest')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_request_items', to='maainventory.itemvariation')),
            ],
            options={
                'db_table': 'item_request_items',
            },
        ),
        migrations.CreateModel(
            name='SupplierStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_stock', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_stock', to='maainventory.item')),
                ('item_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='maainventory.itemrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='maainventory.supplier')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_stock', to='maainventory.itemvariation')),
            ],
            options={
                'db_table': 'supplier_stock',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
