# Generated by Django 6.0 on 2026-01-26 05:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0019_itemrequest_itemrequestitem_supplierstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussed_price', models.DecimalField(decimal_places=2, help_text='Price discussed with supplier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discussed_date', models.DateTimeField(help_text='Date of price discussion')),
                ('notes', models.TextField(blank=True, help_text='Notes about the price discussion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussed_by', models.ForeignKey(help_text='User who had the discussion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_discussions', to=settings.AUTH_USER_MODEL)),
                ('supplier_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_discussions', to='maainventory.supplieritem')),
            ],
            options={
                'verbose_name': 'Price Discussion',
                'verbose_name_plural': 'Price Discussions',
                'db_table': 'supplier_price_discussions',
                'ordering': ['-discussed_date', '-created_at'],
            },
        ),
    ]
