# Generated by Django 6.0 on 2026-01-26 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0020_supplierpricediscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricediscussion',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous price before this discussion', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
