# Generated by Django 6.0 on 2026-01-26

import django.core.validators
from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0021_supplierpricediscussion_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPackagingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name as in sales file', max_length=255)),
                ('boxes_per_unit', models.DecimalField(decimal_places=2, default=1, help_text='Boxes consumed per 1 unit ordered', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wrappers_per_unit', models.DecimalField(decimal_places=2, default=1, help_text='Wrappers consumed per 1 unit ordered', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=deletion.CASCADE, related_name='packaging_rules', to='maainventory.branch')),
                ('item', models.ForeignKey(blank=True, help_text='Linked inventory item if matched', null=True, on_delete=deletion.SET_NULL, related_name='packaging_rules', to='maainventory.item')),
            ],
            options={
                'db_table': 'branch_packaging_rules',
                'ordering': ['branch', 'product_name'],
                'unique_together': {('branch', 'product_name')},
            },
        ),
    ]
