# Generated by Django 6.0 on 2026-01-26

import django.core.validators
from django.db import migrations, models
from django.db.models import deletion


def migrate_packaging_to_items(apps, schema_editor):
    """Migrate boxes_per_unit/wrappers_per_unit to BranchPackagingItem + BranchPackagingRuleItem."""
    BranchPackagingRule = apps.get_model('maainventory', 'BranchPackagingRule')
    BranchPackagingItem = apps.get_model('maainventory', 'BranchPackagingItem')
    BranchPackagingRuleItem = apps.get_model('maainventory', 'BranchPackagingRuleItem')

    for rule in BranchPackagingRule.objects.all():
        branch = rule.branch
        # Create Box packaging item for branch if not exists
        box_item, _ = BranchPackagingItem.objects.get_or_create(
            branch=branch, name='Box', defaults={'display_order': 0}
        )
        # Create Wrapper packaging item for branch if not exists
        wrapper_item, _ = BranchPackagingItem.objects.get_or_create(
            branch=branch, name='Wrapper', defaults={'display_order': 1}
        )
        # Create rule items for boxes and wrappers
        if rule.boxes_per_unit and float(rule.boxes_per_unit) > 0:
            BranchPackagingRuleItem.objects.get_or_create(
                rule=rule, packaging_item=box_item,
                defaults={'quantity_per_unit': rule.boxes_per_unit}
            )
        if rule.wrappers_per_unit and float(rule.wrappers_per_unit) > 0:
            BranchPackagingRuleItem.objects.get_or_create(
                rule=rule, packaging_item=wrapper_item,
                defaults={'quantity_per_unit': rule.wrappers_per_unit}
            )


def reverse_migrate(apps, schema_editor):
    """Reverse: set boxes_per_unit=1, wrappers_per_unit=1 (data loss)."""
    pass  # Can't restore old values; migration will fail if reversing after RemoveField


class Migration(migrations.Migration):

    dependencies = [
        ('maainventory', '0022_add_branch_packaging_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPackagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Box, Wrapper, Bag', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=deletion.CASCADE, related_name='packaging_items', to='maainventory.branch')),
            ],
            options={
                'db_table': 'branch_packaging_items',
                'ordering': ['branch', 'display_order', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BranchPackagingRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, default=1, help_text='Quantity consumed per 1 unit of product', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('packaging_item', models.ForeignKey(on_delete=deletion.CASCADE, related_name='rule_items', to='maainventory.branchpackagingitem')),
                ('rule', models.ForeignKey(on_delete=deletion.CASCADE, related_name='rule_items', to='maainventory.branchpackagingrule')),
            ],
            options={
                'db_table': 'branch_packaging_rule_items',
                'unique_together': {('rule', 'packaging_item')},
            },
        ),
        migrations.RunPython(migrate_packaging_to_items, reverse_migrate),
        migrations.RemoveField(model_name='branchpackagingrule', name='boxes_per_unit'),
        migrations.RemoveField(model_name='branchpackagingrule', name='wrappers_per_unit'),
    ]
